#配置端口号:
server:
  port: 8080

#配置数据库：
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/rnbi?serverTimezone=GMT%2B8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#mybatis-plus:
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
    # 配置JdbcTypeForNull
    jdbc-type-for-null: 'null'
  global-config:
    db-config:
      logic-not-delete-value: 0 # 未删除为 0
      logic-delete-value: 1 # 删了就是 1
    banner: false

STREAM_SECRET: abp7mrpj4hwgs4qdnez7p65nc2ythdgxr3dsy25w9db5s9hb4m65j5pkmpjcrb32